### ISSUE TITLE
Scrolling leads to infinitely zooming in sometimes

### ISSUE THREAD

**Issue by AppearedOne** [Bigeard/Perfect-Night#2]
When opening the site and joining with one device, when I scroll on my computer instead of resizing properly back, it resizes infinitely on the qr code. Scrolling out again leads to infinite zooming away. Cant provide any screenshots right now but let me know if you need me to give more info

**Comment by Bigeard** [comment]
The zoom is only used for development tests, now it can only be used in "dev" mode :)

**Comment by Bigeard** [comment]
Use this link to see the changes: https://bigeard.github.io/Perfect-Night/
